# Generated by Django 2.2.6 on 2019-10-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('label', models.TextField()),
            ],
        ),
    ]
